### ISSUE TITLE
plasmashell uses 100% CPU when octopi-notifier is running with an update available

### ISSUE THREAD

**Issue by AnAkkk** [aarnt/octopi#142]
I've noticed that when I had a AUR update and octopi-notifier was showing it, plasmashell CPU kept increasing until it would use 100%. Killing octopi-notifier immediately made it drop to 0%. Starting it again made it back at 100%.
After updating the package, the icon disappeared and it went back to 0%.

This seem to happen every time an update is available, I've uninstalled octopi-notifier for now.

**Comment by ennokde** [comment]
This happens with all system tray icons. Every time they change their looks it raises memory and CPU consumption. It's a bug in KDE. The only reason it is so obvious with the notifier is that the red and yellow icons are animated.

I would suggest adding an option to go back to the old static images to reduce the severity of the issue  caused by the KDE bug.
That would probably also make those happy that just dont like animations.

**Comment by aarnt** [comment]
Currently, Octopi does not use animated icons. This seems a plasma 5 related bug.

**Comment by nortexoid** [comment]
The icon is clearly animated. It zooms in and out when there's an update. Disabling the animation is a very good idea given cpu usage (and people may find it annoying).

**Comment by E14** [comment]
> The icon is clearly animated. It zooms in and out when there's an update. Disabling the animation is a very good idea given cpu usage (and people may find it annoying).

Is this really from 2015? Just ran into this on Manjaro KDE, and it's quite irritating. It's loading a full CPU core just to animate a tiny icon. Apart from the possible performance penalties, it's especially irritating in summer...

But at least for me, the icon did not originate from octopi package itself, but an octopi-notifier provided by `octopi-notifier-frameworks` package, packaged by @philmmanjaro, maybe he can help?

`octopi-notifier-qt5` does not seem to animate, and so works as intended. Maybe this is even a Manjaro KDE bug at this point...
