### ISSUE TITLE
[cinnamon] terminal not open up

### ISSUE THREAD

**Issue by ghost** [aarnt/octopi#148]
https://gist.github.com/anonymous/6179793c2f0fae657d36

hi,

it could be cinnamon specifik things like octopi-notifier-qt5 but qt4 should work , mainly the issue is
octopi cant call terminal on my side, xterm is installed system use now gnome-terminal as base, but

even i select prefered application to xterm, terminal dont start, it could be cinnamon related stuff.. but just need to find out of people have also this issue...

octopi-notifier ;  qt5 version have blue icons ? or its the cinnamon issue probably so i have to write it up? but its not stable, needs to sleep-timer after reboot to show up on the panel otherwise it dont show up. but have some doing on octopi, icon drops... could be a cinnamon part of story...
Also when update system upgrade also does not shows.
Qt4 version: color is correct,  for moment it did not dropped and update button shows..when want to use the update dialog shows but select terminal , terminal does not open

even i use octopi and want install from terminal or remove, terminal does not open. could be a cinnamon/qt5 issue have also find out what it is, if its more cinnamon related.. then i need to know to go upstream on cinnamon*.

if on other desktop environment works let me know also,

i recently reinstalled cinnamon desktop so could be more cinnamon related 

tried to do debugging with gdb but ehmm fails ...

someone got the same ?

**Comment by losbehamos** [comment]
Hi ghost,

I can confirm that in my case terminal does not open up with octopi in cinnamon when the terminal should be opened with some kind of su command. This means File -> open terminal as root and doing a pacman install or upgrade doesn't work. Aur install and upgrade and open terminal here ( when you right klick on a folder in the files tab) are working without any problem. I tried to launch the gnome-terminal with root privileges without finding anything which works reliably, trying it within a mate session made no difference so I don't think it is cinnamon related. I also tried to configure gksu using sudo instead of su as suggested in this thread https://github.com/aarnt/octopi/issues/118 without reliable results.

Changing the prefered terminal has no effect because gnome terminal is defined in the code (constants.h) as standard for cinnamon. As a workaround for the 0.8.1 release I created a patch which sets the standard terminal for cinnamon to xterm and changes also the QStrings so that xterm is called in a correct way.

The attached src tarball can be extracted and then built with makepkg and already contains the patch.

[octopi-0.8.1-3.src.tar.gz](https://github.com/aarnt/octopi/files/244008/octopi-0.8.1-3.src.tar.gz)

I also need a little delay (15 sec) for the octopi-notifier qt5 shown in tray but I don't have a blue icon.
