### ISSUE TITLE
root login once for each session

### ISSUE THREAD

**Issue by voanhcuoc** [aarnt/octopi#177]
It'll be better if octopi just prompt for root password once each session (from launching the instance to terminate it) like Synaptic does.

Or at least let add an option to enable it.

**Comment by jshand2015** [comment]
this could be a serious security breach.  one must be careful to keep the system as secure as possible

**Comment by voanhcuoc** [comment]
@jshand2015 :disappointed_relieved: oh, so just add an option to enable it, which will ask for authentication to change its state. Some desktop's users don't need such security.

**Comment by aarnt** [comment]
The problem here is Octopi *needs* to retrieve pacman output.
For that, I must execute kdesu in console mode (which disables password keeping).
A workaround for that is to execute Octopi with root (only possible in KDE).
When you use gksu, you can keep the password for the current session.

Whatever other solution I've tried before did not get pacman output (including polkit).
So, if you have any...

**Comment by aarnt** [comment]
Upstream code uses octopi-sudo that can be configure to run with no password.
