### ISSUE TITLE
Octopi doesn't show correctly updates anymore

### ISSUE THREAD

**Issue by michaldybczak** [aarnt/octopi#237]
At the beginning I thought that problem occurs with AUR packages only but not it seems to be present in general.
Here is my thread describing it:
https://forum.manjaro.org/t/octopi-doesnt-show-correctly-updates-anymore/24359

I had to roll-back to the previous version at the moment.

**Comment by philmmanjaro** [comment]
Well, the changes from **v0.8.7** to **v0.8.8** was [this](https://github.com/aarnt/octopi/compare/18bccb8e5b19bce136f3b2fdfaa239360d8b72a7...19eb70e425e57f10e32c120965ebdecf6d9cb684). Maybe some of you do a **git-bisect** to find the issue here. Most likely it was introduced via [9a1d042](https://github.com/aarnt/octopi/commit/9a1d042fb8501fb4ebf448e86989091fee15b750).

**Comment by philmmanjaro** [comment]
Most likely related to https://github.com/aarnt/octopi/issues/235

**Comment by michaldybczak** [comment]
Since this issue was fixed a while ago I close this topic.
