### ISSUE TITLE
Ignored packages

### ISSUE THREAD

**Issue by zethra** [aarnt/octopi#309]
Octopi shows that update are available for a package that is set as ignored in the pacman config.

**Comment by bwendell** [comment]
Can you provide more description (or a screenshot) of where you see this? Is it only this location you see it?

![image](https://user-images.githubusercontent.com/6706358/36336830-5cf2dc14-1340-11e8-830a-54544ffb9f35.png)

**Comment by zethra** [comment]
It would show up in the list that you get when you click the red alien it was counted in the number next to the octopi icon.

**Comment by Vincent43** [comment]
Is this a bug? It shows that update is available because...update is available but it doesn't update it automatically. The info about new package version can be valuable even when automatic updates are ignored (maybe the bug that concerns you was fixed? maybe you want to rebuild new version locally?)

Without this you would never know about changes to ignored packages.

**Comment by zethra** [comment]
In that case I think there should be an option to at least make it so that the octopi notifier doesn't show you have updates if they're only for ignored packages.

**Comment by Vincent43** [comment]
It doesn't show ignored updates in tray already. If it does for for you then you have to provide more info as it isn't reproducible.

**Comment by sheinz** [comment]
If multiple `IgnorePkg` lines are present in `pacman.conf` octopi handles only the first statement.
For example in my pacman.conf:
```
IgnorePkg = dhcpcd
IgnorePkg = xf86-video-intel xorg-server
```
Octopi shows two outdated packages. If I join it into a single statement octopi shows no outdated packages.
