### ISSUE TITLE
AUR with trizen not showing up

### ISSUE THREAD

**Issue by MarianArlt** [aarnt/octopi#324]
Glad to see new AUR helpers are being integrated (Thank you!). Is there any cli option when compiling/installing either octopi or trizen to make them compatible? Or any paths I have to set? Seems Octopi doesn't recognize my Trizen install by default. Alien won't show at all and there's no AUR tab in the options section. Tried to compile Octopi again over my existing install with
```
$ qmake-qt5
$ make
```
without luck. Tried to reinstall Trizen a few times as well.

Arch Linux 4.15.15
Octopi 0.9.0
Trizen 1.47

**Comment by michaldybczak** [comment]
Octopi and Trizen seems to work fine so far. I just discovered the new interface and switched to Tizen from pacaur since it's no longer in development.

Since there is no AUR tab in Octopi, something is wrong with the Octopi itself. For me all looks all right:

![screenshot_20180504_124047](https://user-images.githubusercontent.com/10132958/39624115-602bdb1c-4f98-11e8-820d-2ecc4b648b2f.jpg)

**Comment by kevinsmia1939** [comment]
I can confirm the bug.
I use Artix linux.
Installed trizen but no AUR tab does not showed up.
Install yaourt and it showed up.

**Comment by aarnt** [comment]
Upstream code now always show AUR tab while on Arch Linux compatible distros.
