### ISSUE TITLE
disable auto update repository

### ISSUE THREAD

**Issue by candrapersada** [aarnt/octopi#340]
how to disable auto update, repository manjaro from octopi?

**Comment by nRoof** [comment]
You mean to disable the automatic checking of updates? If Yes, then it seems that removing `/etc/xdg/autostart/octopi-notifier.desktop` will do the job. It will prevent `octopi-notifier` from running at system startup.

Although new releases of this project are not frequent, I still vote for introducing an opiton in the UI to enable/disable automatic checking of updates. For now it looks like PKGBUILD installs `octopi-notifier` by default, and there's no GUI way to disable automatic checking of updates. AFAIK, the workaround mentioned above will stop working after the next update, because the missing file will be recreated.

**Comment by candrapersada** [comment]
yes and add GUI for enable/disable automatic.

**Comment by aarnt** [comment]
Implemented at upstream: Options/Synchronization/Never
