### ISSUE TITLE
Internet avability check is too early

### ISSUE THREAD

**Issue by philmmanjaro** [aarnt/octopi#346]
When you have a WIFI connection the notifier currently checks for internet connection too early. The check needs either to be delayed or improved. Reverting a9d9eb30d37e97369cfc64204fe0bde9e0e29918 fixes it partly.

**Comment by jkmyklebust** [comment]
It's also notifying via a message box instead of using the notification system. Why?

**Comment by demmm** [comment]
To confirm this, the above commit has been reverted in KaOS since May:
https://github.com/KaOSx/apps/commit/990fdd375f93f02f033734c4bf16d3f9716d5142#diff-0b8667833e0381f3eb0b1646bd90258a
https://github.com/KaOSx/apps/commit/4d61c3fb344e5b99cc9bd9cc55830ade3289dbd2#diff-0b8667833e0381f3eb0b1646bd90258a

**Comment by dimdam** [comment]
A few people having issues because of the early availability check (including me): https://forum.manjaro.org/t/octopi-internet-seems-unavailable/48788/21

**Comment by markovic-nikola** [comment]
+1

**Comment by aarnt** [comment]
Changed upstream.
