### ISSUE TITLE
[Suggestion] Add Archcraft support

### ISSUE THREAD

**Issue by Epikest** [aarnt/octopi#488]

**Comment by zoeronen** [comment]
I would like to request if you can also add support for Garuda Linux. Most editions will now ship with Octopi instead of Pamac.
The content of /etc/os-release:

[os-release.txt](https://github.com/aarnt/octopi/files/7187847/os-release.txt)

I actually tried to fork and add it myself but couldn't figure out all the variables that need to be added, they seem to be scattered in different places.

**Comment by aarnt** [comment]
Hi @zoeronen 

Does Garuda uses Arch Linux repositories?
Does it have its own news page?

**Comment by zoeronen** [comment]
Arch repositories + chaotic-aur, which builds from the aur, as well as here https://github.com/orgs/chaotic-aur/repositories?q=&type=&language=&sort= and in gitlab https://gitlab.com/garuda-linux/packages
News could link to forum feed https://forum.garudalinux.org/latest.rss

**Comment by aarnt** [comment]
@zoeronen 
Hmm, I see.
Do you think it is best to link to their forum feed? Sometimes native Arch news has important package news (manual interventions, etc).

**Comment by zoeronen** [comment]
Good idea! If it will encourage users to research there before posting on our forum, it will be a blessing 🙏

**Comment by aarnt** [comment]
Support added upstream.

**Comment by zoeronen** [comment]
So I've tried the current master version on my Garuda and after pressing ctrl+G to refresh the news nothing appears. I thought this was specific to the rss it's pulling but today I noticed the news tab behaves the same on my Manjaro install. Not sure if I should open a new issue for this.

**Comment by aarnt** [comment]
Did you install the new generated octopi binary at "/usr/bin" ?
